### ISSUE TITLE
SSH free accounts NULL error

### ISSUE THREAD

**Issue by jamiees2** [picoCTF/picoCTF-Platform-2#48]
When I attempt to have free accounts, and run `./daemon_manager shell_accounts`, I get the following error:

```
Traceback (most recent call last):
  File "./daemon_manager.py", line 48, in <module>
    main()
  File "./daemon_manager.py", line 46, in main
    run_modules(selected_modules, args.interval)
  File "./daemon_manager.py", line 15, in run_modules
    module.run()
  File "daemons/shell_accounts.py", line 78, in run
    db.ssh.insert(accounts)
  File "/usr/local/lib/python3.4/dist-packages/pymongo/collection.py", line 412, in insert
    self.uuid_subtype, client)
  File "/usr/local/lib/python3.4/dist-packages/pymongo/mongo_client.py", line 1121, in _send_message
    rv = self.__check_response_to_last_error(response, command)
  File "/usr/local/lib/python3.4/dist-packages/pymongo/mongo_client.py", line 1062, in __check_response_to_last_error
    raise DuplicateKeyError(details["err"], code, result)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error index: test-ctf.ssh.$unique ssh tid  dup key: { : null }
```

**Comment by jamiees2** [comment]
Fixed by adding `sparse=True` to the "tid" index in db.ssh.
